version: "3"
services:
  postgresql:
    image: postgres:14
    container_name: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "6432:5432"
    networks:
      - shaple-builder-chatbot-network
    restart: always

networks:
  shaple-builder-chatbot-network:
    driver: bridge
