import type {Metadata} from "next";
import {Inter} from "next/font/google";
import "./globals.css";
import classNames from "classnames";
import Script from "next/script";

const inter = Inter({subsets: ["latin"]});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
                                     children,
                                   }: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="h-full bg-white">
      <body className={classNames(inter.className, "flex flex-row justify-center h-full w-full")}>
        {children}
      </body>
    </html>
  );
}
