name: CI
run-name: ${{ github.actor }} is testing MAY🚀
on: [pull_request, push]
jobs:
  Run-Unit-Tests:
    runs-on: [self-hosted, Linux]
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
        with:
          submodules: recursive
          token: ${{ secrets.PAUST_GITHUB_TOKEN }}
      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Setup yarn
        run: |
          npm install -g yarn
      - name: Install
        run: |
          yarn install
      - name: Setup kind cluster
        run: |
          export PATH=/home/paust/go/bin/:$PATH
          yarn setup
      - name: Run tests
        run: |
          yarn test
      - name: Tear down kind cluster
        if: success() || failure()
        run: |
          export PATH=/home/paust/go/bin/:$PATH
          yarn teardown